global:
  name: consul

server:
  replicas: 1
  storage:
    enabled: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  affinity: null

client:
  enabled: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

ui:
  enabled: true

connectInject:
  enabled: false

controller:
  enabled: false

syncCatalog:
  enabled: false

dns:
  enabled: true
